# Global site settings for GitHub Pages
title: Spectomate
tagline: Python Package Management Format Converter
description: A tool for converting projects between different Python package management formats (pip, conda, poetry)
url: https://spectomate.github.io
baseurl: /python

# SEO settings
author:
  name: Spectomate Team
  url: https://github.com/spectomate
logo: /docs/diagrams/logo.png
lang: en_US
locale: en_US

# Social media
social:
  name: Spectomate
  links:
    - https://github.com/spectomate/python

# GitHub metadata
repository: spectomate/python
github:
  is_project_page: true
  repository_url: https://github.com/spectomate/python
  owner_url: https://github.com/spectomate
  owner_name: Spectomate

# Theme settings
theme: jekyll-theme-cayman
show_downloads: true

# Navigation
nav:
  - title: Home
    url: /
  - title: Documentation
    url: /docs/
  - title: Architecture
    url: /docs/ARCHITECTURE.html
  - title: Converters
    url: /docs/CONVERTERS.html
  - title: Schemas
    url: /docs/SCHEMAS.html
  - title: Testing
    url: /docs/TESTING.html
  - title: GitHub
    url: https://github.com/spectomate/python

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "docs"
    values:
      layout: page
      sidebar: docs
