# Jekyll configuration for docs directory
title: Spectomate Documentation
description: Comprehensive documentation for the Spectomate Python package format converter
url: https://spectomate.github.io
baseurl: /python/docs
author:
  name: Tom Sapletta
  url: https://github.com/spectomate
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# GitHub metadata
repository: spectomate/python
github:
  is_project_page: true
  repository_url: https://github.com/spectomate/python
  owner_url: https://github.com/spectomate
  owner_name: Tom Sapletta

# Build settings
markdown: kramdown
highlighter: rouge
