version: '3'

services:
  web:
    image: spectomate/converter:latest
    container_name: spectomate-web
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - spectomate-network
    volumes:
      - ./logs:/app/logs

  nginx:
    image: nginx:alpine
    container_name: spectomate-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - web
    networks:
      - spectomate-network

networks:
  spectomate-network:
    driver: bridge
